spring.application.name=MostrarCanciones

#Conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/canciones_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion para que Spring encuentre los JSPs
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

# Forzar a Spring Boot a reconocer la carpeta webapp en modo desarrollo
server.servlet.context-path=/
server.port=8080